### ISSUE TITLE
Lower bound on the OCaml version?

### ISSUE THREAD

**Issue by gallais** [bobatkey/sott#1]
You may want to mention in the README that you need [OCaml version 4.03](https://ocaml.org/releases/4.03.html) or newer because you're using inline records in algebraic datatypes. I tried to compile the project with [my version from debian stable](https://packages.debian.org/stretch/ocaml) and got a syntax error.

**Comment by bobatkey** [comment]
Good point. I've pushed an update to the README to mention this.
